Chapter 3 and beginning of chapter 4.
ro-msg-spring-training/online-shop-SirVsbi pull request #1
Opened 2021-04-09 11:42 UTC by SirVsbi

The code so far contains:

-  all the JPA entities and flywal migration files. 
- basic GET AND POST endpoints for products and suppliers (so, no /{id} endpoints yet) 
- repo, service, dto, converter, controller for products & suppliers

2021-04-09 14:18 UTC, cristinacalbaza requested changes

2021-04-09 14:18 UTC, cristinacalbaza commented on src/main/java/ro/msg/learning/shop/controller/ProductController.java
> +            System.out.println(productConverter.dtoToModel(productDto));
Remove these 2 lines.

2021-04-09 14:18 UTC, cristinacalbaza commented on src/main/java/ro/msg/learning/shop/model/ProductCategory.java
> +    private List<Product> products;
As we discussed today, please remove the list from here.

2021-04-09 14:18 UTC, cristinacalbaza commented on src/main/java/ro/msg/learning/shop/controller/ProductCategoryController.java
> +                (ArrayList<ProductCategoryDto>) productCategoryConverter.convertModelToDto(productCategoryService.getAllProductCategories())
You should not access the Data Model from Controller. So, as it is already suggested in Training material, your service methods should receive as parameters a DTO object and return also a DTO. Please change  this for all Services in the app.

2021-04-12 11:29 UTC, SirVsbi commented
Fixed the issues. Implemented the rest of the REST API only for the suppliers.

2021-04-14 07:49 UTC, cristinacalbaza approved these changes

2021-04-14 07:49 UTC, merged